---
title: "demo2-mesh"
author: "Haiyi Shi (hshi786)"
date: "12/10/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(viridis)
library(ggplot2)
library(cowplot)
library(dplyr)
library(INLA)
```


## Mesh 1
```{r}
source("mesh.sim.R")
source("mesh.pro.R")
source("functions.R")
domain <- 3 * cbind(c(0,1,1,0,0), c(0,0,1,1,0))
mesh1 <- mesh.sim(domain, c(0.3, 0.4), 0.005, c(0.05, -0.1))
plot(mesh1$mesh, asp=1)
```

## Mesh 2
```{r}
mesh2 <- mesh.sim(domain, c(0.3, 0.4), 0.1, c(0.05, -0.1))
plot(mesh2$mesh, asp=1)
```


## Mesh 3
```{r}
mesh3 <- mesh.sim(domain, c(0.3, 0.4), 0.1, c(0.3, 0.8))
plot(mesh3$mesh, asp=1)
```


## Mesh 4

```{r}
mesh4 <- mesh.sim(domain, c(0.3, 0.4), 0.1, c(0.5, 1))
plot(mesh4$mesh, asp=1)
```


## Mesh Assessment

```{r, message=FALSE}
mval <- c(c(0.3, 0.4), 0.005, c(0.05, -0.1),
          c(0.3, 0.4), 0.1, c(0.05, -0.1),
          c(0.3, 0.4), 0.1, c(0.3, 0.8),
          c(0.3, 0.4), 0.1, c(0.5, 1))
mesh.mat <- matrix(mval, ncol = 5, byrow = TRUE)
ls.mesh <- mesh.pro(domain, mesh.mat)
```


## Triangulation Attributes

```{r, message=FALSE}
attrs <- vector("list", length = nrow(mesh.mat))
angles <- vector("list", length = nrow(mesh.mat))
radius <- vector("list", length = nrow(mesh.mat))
for(x in 1:nrow(mesh.mat)){
  attrs[[x]] <- get_triag_attributes(ls.mesh[[x]]$mesh)
  radius[[x]] <- data.frame(radius_edge=attrs[[x]]$triangles$re, 
                            radius_ratio=attrs[[x]]$triangles$rr)
  angles[[x]] <- attrs[[x]]$angles
}
```


## Summary of Angles

```{r}
labs <- c()
num.angs <- c()
pro.acute <- c()
pro.obtuse <- c()
pro.medium <- c()
for(i in 1:nrow(mesh.mat)){
  labs[i] <- paste0("Mesh", i)
  num.angs[i] <- nrow(attrs[[i]]$angles)
  pro.acute[i] <- sum(apply(attrs[[i]]$angles, 1, function(x) any(x < 30)))/num.angs[i]
  pro.obtuse[i] <- sum(apply(attrs[[i]]$angles, 1, function(x) any(x > 90)))/num.angs[i]
  pro.medium[i] <- sum(apply(attrs[[i]]$angles, 1, function(x) any(x > 50 & x < 65)))/num.angs[i]
}
tri.sum <- data.frame(Mesh=labs, num.angs=num.angs, pro.acute=pro.acute, 
                      pro.obtuse=pro.obtuse, pro.medium=pro.medium)
knitr::kable(tri.sum, align = "ccccc", booktabs = TRUE, digits = 4)
```


## Summary of Mesh

```{r}
ls.time <- vector(mode="list", length = nrow(mesh.mat))
ls.argu <- vector(mode="list", length = nrow(mesh.mat))
labs <- c()
vertices <- c()
for (y in 1:nrow(mesh.mat)) {
  ls.time[[y]] <- ls.mesh[[y]]$time
  ls.argu[[y]] <- ls.mesh[[y]]$arguments[-1]
  vertices[y] <- ls.mesh[[y]]$mesh$n
  labs[y] <- paste0("Mesh", y)
}
mesh.df <- cbind(data.frame(matrix(unlist(ls.time), ncol = 5, byrow = TRUE)),
                 data.frame(matrix(unlist(ls.argu), ncol = 5, byrow = TRUE)))

mesh.sum <- data.frame(Mesh=labs, Elapsed=mesh.df[[3]], Vertices=vertices, 
           Max.edge=paste0(mesh.df[[6]], "; ", mesh.df[[7]]), Cutoff=mesh.df[[8]], 
           Offset=paste0(mesh.df[[9]], "; ", mesh.df[[10]]), num.angs=num.angs,
           pro.acute=pro.acute, pro.obtuse=pro.obtuse, pro.medium=pro.medium)
knitr::kable(mesh.sum, align = "ccccccccc", booktabs = TRUE, digits = 4)
```


### Plot of Angles

```{r}
allradius <- bind_rows(radius)
allradius$mesh <- rep(paste0("Mesh", 1:nrow(mesh.mat)), times=sapply(radius, nrow))
levels <- paste0("Mesh", 1:nrow(mesh.mat))
allradius$meshes <- factor(allradius$mesh, levels = levels)
```


### The radius-edge ratio  R/l_min ,1/sqrt(3) for an equilateral triangle.

```{r, fig.width=10, fig.height=6}
ggplot(data=allradius, aes(x=meshes,y=radius_edge, group=meshes, fill=meshes)) +
  geom_violin(position="dodge", alpha=0.5, trim = FALSE) +
  geom_boxplot(width=0.1, color="grey", alpha=0.2) +
  coord_flip() +
  geom_hline(yintercept = 1/sqrt(3), linetype="dashed",size=1) +
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  scale_fill_brewer(palette="Paired") +
  labs(title = "Radius-edge") +
  theme_light() +
  theme(legend.position="none", axis.title.y=element_blank())
```


### The radius ratio r/R, 1/2 for an equilateral triangle.

```{r, fig.width=10, fig.height=6}
ggplot(data=allradius, aes(x=meshes,y=radius_ratio, group=meshes, fill=meshes)) +
  geom_violin(position="dodge", alpha=0.5, trim = FALSE) +
  geom_boxplot(width=0.1, color="grey", alpha=0.2) +
  coord_flip() +
  geom_hline(yintercept = 1/2, linetype="dashed",size=1) +
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  scale_fill_brewer(palette="Paired") +
  labs(title = "Radius-ratio") +
  theme_light() +
  theme(legend.position="none", axis.title.y=element_blank()) 
```


### Plotting

```{r, fig.width=10, fig.height=6}
levels <- paste0("Mesh", 1:nrow(mesh.mat))
mesh.sum$meshes <- factor(mesh.sum$Mesh, levels = levels)
t <- ggplot(mesh.sum, aes(x=meshes, y=pro.acute)) +
  geom_point() +
  theme_linedraw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

n <- ggplot(mesh.sum, aes(x=meshes, y=pro.obtuse)) +
  geom_point() +
  theme_linedraw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

tt <- ggplot(mesh.sum, aes(x=meshes, y=pro.medium)) +
  geom_point() +
  theme_linedraw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_text(angle = 45, hjust = 1))

title <- ggdraw() + draw_label("Mesh Assessment", fontface='bold')
bottom_row <- plot_grid(t, n, ncol = 2, labels = "AUTO")
plot_grid(title, bottom_row, tt, nrow = 3, 
          labels = c("", "", "C"), rel_heights = c(0.2, 1, 1))
```

